version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # A versão 3 com o plugin de gerenciamento
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"  # Porta padrão de comunicação AMQP
      - "15672:15672"  # Porta do plugin de gerenciamento
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq  # Persistência de dados
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local